{{- if .Values.rbac.createRole }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.config.kubernetes.namespace }}
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps", "serviceaccounts"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["persistentvolumes", "persistentvolumeclaims"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["pods", "services", "replicationcontrollers"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["pods/log"] 
  verbs: ["get", "list"] 
- apiGroups: ["route.openshift.io"]
  resources: ["routes"]
  verbs:  ["*"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["*"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["*"]
- apiGroups: ["image.openshift.io"]
  resources: ["imagestreams/layers"]
  verbs: ["update", "get"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create", "get"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["create", "delete", "get"]
- apiGroups: [""]
  resources: ["resourcequotas"]
  verbs: ["create", "get", "list", "update", "delete"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles"]
  verbs: ["create", "get", "list"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["clusterrolebindings"]
  verbs: ["create", "get", "list", "update"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["rolebindings"]
  verbs: ["create", "get", "list", "update"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["resourcequotas"]
  verbs: ["create", "get", "list", "update", "delete"]
  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.config.kubernetes.namespace }}
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps", "serviceaccounts"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["persistentvolumes", "persistentvolumeclaims"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["pods", "services", "replicationcontrollers"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["pods/log"] 
  verbs: ["get", "list"] 
- apiGroups: ["route.openshift.io"]
  resources: ["routes"]
  verbs:  ["*"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["*"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["*"]
- apiGroups: ["image.openshift.io"]
  resources: ["imagestreams/layers"]
  verbs: ["update", "get"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create", "get"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles"]
  verbs: ["create", "get", "list"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["rolebindings"]
  verbs: ["create", "get", "list"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["resourcequotas"]
  verbs: ["create", "get", "list", "update", "delete"]
{{- end }}